name: Fuzz

on:
  # Run every hour at X:17
  schedule:
  - cron: '17 * * * *'

  # Run on every push to main.
  push:
    branches: ['main']
 
  # Allow manual runs. 
  workflow_dispatch:

# Cancel any in-progress runs for the same PR or SHA.
concurrency:
  group: fuzz-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  fuzz:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - run: |
        go install golang.org/dl/go1.18beta1@latest
        go1.18beta1 download

    - run: go1.18beta1 test -fuzz=Fuzz -fuzztime=30m

    # If any new testdata was generated, open a PR.
    - uses: peter-evans/create-pull-request@v3
      with:
        add-paths: testdata
        title: New testdata
        assignees: imjasonh
